#
# eBPF
#

CONFIG_KERNEL_BPF_SYSCALL=y
CONFIG_KERNEL_BPF_JIT=y
CONFIG_KERNEL_BPF_JIT_ALWAYS_ON=y

CONFIG_KERNEL_CGROUPS=y
CONFIG_KERNEL_CGROUP_BPF=y

CONFIG_KERNEL_NET_CLS_BPF=y
CONFIG_KERNEL_NET_ACT_BPF=y

CONFIG_KERNEL_BPF_EVENTS=y


#
# XDP
#

CONFIG_KERNEL_XDP_SOCKETS=y
CONFIG_PACKAGE_kmod-xdp-sockets-diag=y


#
# DAED
#

CONFIG_PACKAGE_kmod-tun=y

CONFIG_PACKAGE_kmod-nft-tproxy=y
CONFIG_PACKAGE_kmod-nft-socket=y


#
# DNS
#

CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_adguardhome=y


#
# VPN
#

CONFIG_PACKAGE_wireguard-tools=y
CONFIG_PACKAGE_kmod-wireguard=y


#
# Tools
#

CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_tcpdump=y
CONFIG_PACKAGE_bpftool=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_ca-bundle=y
CONFIG_PACKAGE_ca-certificates=y
